/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.Address = factory(root.Apicreativehubio.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Address model module.
   * @module model/Address
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Address</code>.
   * @alias module:model/Address
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param line1 {String} 
   * @param postCode {String} 
   * @param phoneNumber {String} 
   */
  var exports = function(firstName, lastName, line1, postCode, phoneNumber) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.line1 = line1;
    this.postCode = postCode;
    this.phoneNumber = phoneNumber;
  };

  /**
   * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Address} obj Optional instance to populate.
   * @return {module:model/Address} The populated <code>Address</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('FirstName'))
        obj.firstName = ApiClient.convertToType(data['FirstName'], 'String');
      if (data.hasOwnProperty('LastName'))
        obj.lastName = ApiClient.convertToType(data['LastName'], 'String');
      if (data.hasOwnProperty('Line1'))
        obj.line1 = ApiClient.convertToType(data['Line1'], 'String');
      if (data.hasOwnProperty('Line2'))
        obj.line2 = ApiClient.convertToType(data['Line2'], 'String');
      if (data.hasOwnProperty('Town'))
        obj.town = ApiClient.convertToType(data['Town'], 'String');
      if (data.hasOwnProperty('County'))
        obj.county = ApiClient.convertToType(data['County'], 'String');
      if (data.hasOwnProperty('PostCode'))
        obj.postCode = ApiClient.convertToType(data['PostCode'], 'String');
      if (data.hasOwnProperty('CountryId'))
        obj.countryId = ApiClient.convertToType(data['CountryId'], 'Number');
      if (data.hasOwnProperty('CountryCode'))
        obj.countryCode = ApiClient.convertToType(data['CountryCode'], 'String');
      if (data.hasOwnProperty('CountryName'))
        obj.countryName = ApiClient.convertToType(data['CountryName'], 'String');
      if (data.hasOwnProperty('PhoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['PhoneNumber'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} line1
   */
  exports.prototype.line1 = undefined;

  /**
   * @member {String} line2
   */
  exports.prototype.line2 = undefined;

  /**
   * @member {String} town
   */
  exports.prototype.town = undefined;

  /**
   * @member {String} county
   */
  exports.prototype.county = undefined;

  /**
   * @member {String} postCode
   */
  exports.prototype.postCode = undefined;

  /**
   * @member {Number} countryId
   */
  exports.prototype.countryId = undefined;

  /**
   * @member {String} countryCode
   */
  exports.prototype.countryCode = undefined;

  /**
   * @member {String} countryName
   */
  exports.prototype.countryName = undefined;

  /**
   * @member {String} phoneNumber
   */
  exports.prototype.phoneNumber = undefined;


  return exports;

}));
