/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IFilterDescriptor', 'model/SortDescriptor'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IFilterDescriptor'), require('./SortDescriptor'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.CollectionRequest = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.IFilterDescriptor, root.Apicreativehubio.SortDescriptor);
  }
}(this, function(ApiClient, IFilterDescriptor, SortDescriptor) {
  'use strict';

  /**
   * The CollectionRequest model module.
   * @module model/CollectionRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CollectionRequest</code>.
   * @alias module:model/CollectionRequest
   * @class
   * @param page {Number} 
   * @param pageSize {Number} 
   */
  var exports = function(page, pageSize) {
    this.page = page;
    this.pageSize = pageSize;
  };

  /**
   * Constructs a <code>CollectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectionRequest} obj Optional instance to populate.
   * @return {module:model/CollectionRequest} The populated <code>CollectionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Page'))
        obj.page = ApiClient.convertToType(data['Page'], 'Number');
      if (data.hasOwnProperty('PageSize'))
        obj.pageSize = ApiClient.convertToType(data['PageSize'], 'Number');
      if (data.hasOwnProperty('Filter'))
        obj.filter = IFilterDescriptor.constructFromObject(data['Filter']);
      if (data.hasOwnProperty('Sorts'))
        obj.sorts = ApiClient.convertToType(data['Sorts'], [SortDescriptor]);
    }
    return obj;
  }

  /**
   * @member {Number} page
   */
  exports.prototype.page = undefined;

  /**
   * @member {Number} pageSize
   */
  exports.prototype.pageSize = undefined;

  /**
   * @member {module:model/IFilterDescriptor} filter
   */
  exports.prototype.filter = undefined;

  /**
   * @member {Array.<module:model/SortDescriptor>} sorts
   */
  exports.prototype.sorts = undefined;


  return exports;

}));
