/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Country'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Country'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.CollectionResultOfCountry = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.Country);
  }
}(this, function(ApiClient, Country) {
  'use strict';

  /**
   * The CollectionResultOfCountry model module.
   * @module model/CollectionResultOfCountry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CollectionResultOfCountry</code>.
   * @alias module:model/CollectionResultOfCountry
   * @class
   * @param total {Number} 
   */
  var exports = function(total) {
    this.total = total;
  };

  /**
   * Constructs a <code>CollectionResultOfCountry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectionResultOfCountry} obj Optional instance to populate.
   * @return {module:model/CollectionResultOfCountry} The populated <code>CollectionResultOfCountry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Data'))
        obj.data = ApiClient.convertToType(data['Data'], [Country]);
      if (data.hasOwnProperty('Total'))
        obj.total = ApiClient.convertToType(data['Total'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Country>} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {Number} total
   */
  exports.prototype.total = undefined;


  return exports;

}));
