/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterLogicalOperator', 'model/IFilterDescriptor'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterLogicalOperator'), require('./IFilterDescriptor'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.CompositeFilterDescriptor = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.FilterLogicalOperator, root.Apicreativehubio.IFilterDescriptor);
  }
}(this, function(ApiClient, FilterLogicalOperator, IFilterDescriptor) {
  'use strict';

  /**
   * The CompositeFilterDescriptor model module.
   * @module model/CompositeFilterDescriptor
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CompositeFilterDescriptor</code>.
   * @alias module:model/CompositeFilterDescriptor
   * @class
   * @extends module:model/IFilterDescriptor
   * @param logicalOperator {module:model/FilterLogicalOperator} 
   */
  var exports = function(logicalOperator) {
    IFilterDescriptor.call(this);
    this.logicalOperator = logicalOperator;
  };

  /**
   * Constructs a <code>CompositeFilterDescriptor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompositeFilterDescriptor} obj Optional instance to populate.
   * @return {module:model/CompositeFilterDescriptor} The populated <code>CompositeFilterDescriptor</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      IFilterDescriptor.constructFromObject(data, obj);
      if (data.hasOwnProperty('LogicalOperator'))
        obj.logicalOperator = FilterLogicalOperator.constructFromObject(data['LogicalOperator']);
      if (data.hasOwnProperty('FilterDescriptors'))
        obj.filterDescriptors = ApiClient.convertToType(data['FilterDescriptors'], [IFilterDescriptor]);
    }
    return obj;
  }

  exports.prototype = Object.create(IFilterDescriptor.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {module:model/FilterLogicalOperator} logicalOperator
   */
  exports.prototype.logicalOperator = undefined;

  /**
   * @member {Array.<module:model/IFilterDescriptor>} filterDescriptors
   */
  exports.prototype.filterDescriptors = undefined;


  return exports;

}));
