/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.DeliveryOption = factory(root.Apicreativehubio.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DeliveryOption model module.
   * @module model/DeliveryOption
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeliveryOption</code>.
   * @alias module:model/DeliveryOption
   * @class
   * @param id {Number} 
   * @param branchId {Number} 
   * @param deliveryChargeExcludingSalesTax {Number} 
   * @param deliveryChargeSalesTax {Number} 
   */
  var exports = function(id, branchId, deliveryChargeExcludingSalesTax, deliveryChargeSalesTax) {
    this.id = id;
    this.branchId = branchId;
    this.deliveryChargeExcludingSalesTax = deliveryChargeExcludingSalesTax;
    this.deliveryChargeSalesTax = deliveryChargeSalesTax;
  };

  /**
   * Constructs a <code>DeliveryOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeliveryOption} obj Optional instance to populate.
   * @return {module:model/DeliveryOption} The populated <code>DeliveryOption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('BranchId'))
        obj.branchId = ApiClient.convertToType(data['BranchId'], 'Number');
      if (data.hasOwnProperty('BranchName'))
        obj.branchName = ApiClient.convertToType(data['BranchName'], 'String');
      if (data.hasOwnProperty('Method'))
        obj.method = ApiClient.convertToType(data['Method'], 'String');
      if (data.hasOwnProperty('DeliveryTime'))
        obj.deliveryTime = ApiClient.convertToType(data['DeliveryTime'], 'String');
      if (data.hasOwnProperty('DeliveryChargeExcludingSalesTax'))
        obj.deliveryChargeExcludingSalesTax = ApiClient.convertToType(data['DeliveryChargeExcludingSalesTax'], 'Number');
      if (data.hasOwnProperty('DeliveryChargeSalesTax'))
        obj.deliveryChargeSalesTax = ApiClient.convertToType(data['DeliveryChargeSalesTax'], 'Number');
      if (data.hasOwnProperty('EstimatedDeliveryDateFrom'))
        obj.estimatedDeliveryDateFrom = ApiClient.convertToType(data['EstimatedDeliveryDateFrom'], 'Date');
      if (data.hasOwnProperty('EstimatedDeliveryDateTo'))
        obj.estimatedDeliveryDateTo = ApiClient.convertToType(data['EstimatedDeliveryDateTo'], 'Date');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} branchId
   */
  exports.prototype.branchId = undefined;

  /**
   * @member {String} branchName
   */
  exports.prototype.branchName = undefined;

  /**
   * @member {String} method
   */
  exports.prototype.method = undefined;

  /**
   * @member {String} deliveryTime
   */
  exports.prototype.deliveryTime = undefined;

  /**
   * @member {Number} deliveryChargeExcludingSalesTax
   */
  exports.prototype.deliveryChargeExcludingSalesTax = undefined;

  /**
   * @member {Number} deliveryChargeSalesTax
   */
  exports.prototype.deliveryChargeSalesTax = undefined;

  /**
   * @member {Date} estimatedDeliveryDateFrom
   */
  exports.prototype.estimatedDeliveryDateFrom = undefined;

  /**
   * @member {Date} estimatedDeliveryDateTo
   */
  exports.prototype.estimatedDeliveryDateTo = undefined;


  return exports;

}));
