/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/OrderItemRequest', 'model/OrderRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Address'), require('./OrderItemRequest'), require('./OrderRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrderEmbryonicRequest = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.Address, root.Apicreativehubio.OrderItemRequest, root.Apicreativehubio.OrderRequest);
  }
}(this, function(ApiClient, Address, OrderItemRequest, OrderRequest) {
  'use strict';

  /**
   * The OrderEmbryonicRequest model module.
   * @module model/OrderEmbryonicRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderEmbryonicRequest</code>.
   * @alias module:model/OrderEmbryonicRequest
   * @class
   * @extends module:model/OrderRequest
   * @param id {Number} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param email {String} 
   * @param shippingAddress {module:model/Address} 
   * @param orderItems {Array.<module:model/OrderItemRequest>} 
   */
  var exports = function(id, firstName, lastName, email, shippingAddress, orderItems) {
    OrderRequest.call(this, id, firstName, lastName, email, shippingAddress, orderItems);
  };

  /**
   * Constructs a <code>OrderEmbryonicRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderEmbryonicRequest} obj Optional instance to populate.
   * @return {module:model/OrderEmbryonicRequest} The populated <code>OrderEmbryonicRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      OrderRequest.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(OrderRequest.prototype);
  exports.prototype.constructor = exports;

  return exports;

}));
