/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrderItemBase = factory(root.Apicreativehubio.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The OrderItemBase model module.
   * @module model/OrderItemBase
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderItemBase</code>.
   * @alias module:model/OrderItemBase
   * @class
   * @param id {Number} 
   * @param productId {Number} 
   * @param printOptionId {Number} 
   * @param quantity {Number} 
   */
  var exports = function(id, productId, printOptionId, quantity) {
    this.id = id;
    this.productId = productId;
    this.printOptionId = printOptionId;
    this.quantity = quantity;
  };

  /**
   * Constructs a <code>OrderItemBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItemBase} obj Optional instance to populate.
   * @return {module:model/OrderItemBase} The populated <code>OrderItemBase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('ProductId'))
        obj.productId = ApiClient.convertToType(data['ProductId'], 'Number');
      if (data.hasOwnProperty('PrintOptionId'))
        obj.printOptionId = ApiClient.convertToType(data['PrintOptionId'], 'Number');
      if (data.hasOwnProperty('Quantity'))
        obj.quantity = ApiClient.convertToType(data['Quantity'], 'Number');
      if (data.hasOwnProperty('ExternalReference'))
        obj.externalReference = ApiClient.convertToType(data['ExternalReference'], 'String');
      if (data.hasOwnProperty('ExternalSku'))
        obj.externalSku = ApiClient.convertToType(data['ExternalSku'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} productId
   */
  exports.prototype.productId = undefined;

  /**
   * @member {Number} printOptionId
   */
  exports.prototype.printOptionId = undefined;

  /**
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * @member {String} externalReference
   */
  exports.prototype.externalReference = undefined;

  /**
   * @member {String} externalSku
   */
  exports.prototype.externalSku = undefined;


  return exports;

}));
