/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Address'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrderBase = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.Address);
  }
}(this, function(ApiClient, Address) {
  'use strict';

  /**
   * The OrderBase model module.
   * @module model/OrderBase
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderBase</code>.
   * @alias module:model/OrderBase
   * @class
   * @param id {Number} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param email {String} 
   * @param shippingAddress {module:model/Address} 
   */
  var exports = function(id, firstName, lastName, email, shippingAddress) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.shippingAddress = shippingAddress;
  };

  /**
   * Constructs a <code>OrderBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderBase} obj Optional instance to populate.
   * @return {module:model/OrderBase} The populated <code>OrderBase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('ExternalReference'))
        obj.externalReference = ApiClient.convertToType(data['ExternalReference'], 'String');
      if (data.hasOwnProperty('FirstName'))
        obj.firstName = ApiClient.convertToType(data['FirstName'], 'String');
      if (data.hasOwnProperty('LastName'))
        obj.lastName = ApiClient.convertToType(data['LastName'], 'String');
      if (data.hasOwnProperty('Email'))
        obj.email = ApiClient.convertToType(data['Email'], 'String');
      if (data.hasOwnProperty('MessageToLab'))
        obj.messageToLab = ApiClient.convertToType(data['MessageToLab'], 'String');
      if (data.hasOwnProperty('ShippingAddress'))
        obj.shippingAddress = Address.constructFromObject(data['ShippingAddress']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} externalReference
   */
  exports.prototype.externalReference = undefined;

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} messageToLab
   */
  exports.prototype.messageToLab = undefined;

  /**
   * @member {module:model/Address} shippingAddress
   */
  exports.prototype.shippingAddress = undefined;


  return exports;

}));
