/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderItemBase', 'model/PrintOption', 'model/Product'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderItemBase'), require('./PrintOption'), require('./Product'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrderItemResponse = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.OrderItemBase, root.Apicreativehubio.PrintOption, root.Apicreativehubio.Product);
  }
}(this, function(ApiClient, OrderItemBase, PrintOption, Product) {
  'use strict';

  /**
   * The OrderItemResponse model module.
   * @module model/OrderItemResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderItemResponse</code>.
   * @alias module:model/OrderItemResponse
   * @class
   * @extends module:model/OrderItemBase
   * @param id {Number} 
   * @param productId {Number} 
   * @param printOptionId {Number} 
   * @param quantity {Number} 
   */
  var exports = function(id, productId, printOptionId, quantity) {
    OrderItemBase.call(this, id, productId, printOptionId, quantity);
  };

  /**
   * Constructs a <code>OrderItemResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItemResponse} obj Optional instance to populate.
   * @return {module:model/OrderItemResponse} The populated <code>OrderItemResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      OrderItemBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('Product'))
        obj.product = Product.constructFromObject(data['Product']);
      if (data.hasOwnProperty('PrintOption'))
        obj.printOption = PrintOption.constructFromObject(data['PrintOption']);
    }
    return obj;
  }

  exports.prototype = Object.create(OrderItemBase.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {module:model/Product} product
   */
  exports.prototype.product = undefined;

  /**
   * @member {module:model/PrintOption} printOption
   */
  exports.prototype.printOption = undefined;


  return exports;

}));
