/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/OrderBase', 'model/OrderItemResponse', 'model/OrderState'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Address'), require('./OrderBase'), require('./OrderItemResponse'), require('./OrderState'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrderResponse = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.Address, root.Apicreativehubio.OrderBase, root.Apicreativehubio.OrderItemResponse, root.Apicreativehubio.OrderState);
  }
}(this, function(ApiClient, Address, OrderBase, OrderItemResponse, OrderState) {
  'use strict';

  /**
   * The OrderResponse model module.
   * @module model/OrderResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderResponse</code>.
   * @alias module:model/OrderResponse
   * @class
   * @extends module:model/OrderBase
   * @param id {Number} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param email {String} 
   * @param shippingAddress {module:model/Address} 
   * @param orderItems {Array.<module:model/OrderItemResponse>} 
   * @param orderState {module:model/OrderState} 
   * @param dateCreated {Date} 
   * @param printCostExcludingSalesTax {Number} 
   * @param printCostSalesTax {Number} 
   * @param totalExcludingSalesTax {Number} 
   * @param totalSalesTax {Number} 
   * @param isPaid {Boolean} 
   */
  var exports = function(id, firstName, lastName, email, shippingAddress, orderItems, orderState, dateCreated, printCostExcludingSalesTax, printCostSalesTax, totalExcludingSalesTax, totalSalesTax, isPaid) {
    OrderBase.call(this, id, firstName, lastName, email, shippingAddress);
    this.orderItems = orderItems;
    this.orderState = orderState;
    this.dateCreated = dateCreated;
    this.printCostExcludingSalesTax = printCostExcludingSalesTax;
    this.printCostSalesTax = printCostSalesTax;
    this.totalExcludingSalesTax = totalExcludingSalesTax;
    this.totalSalesTax = totalSalesTax;
    this.isPaid = isPaid;
  };

  /**
   * Constructs a <code>OrderResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderResponse} obj Optional instance to populate.
   * @return {module:model/OrderResponse} The populated <code>OrderResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      OrderBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('OrderItems'))
        obj.orderItems = ApiClient.convertToType(data['OrderItems'], [OrderItemResponse]);
      if (data.hasOwnProperty('OrderState'))
        obj.orderState = OrderState.constructFromObject(data['OrderState']);
      if (data.hasOwnProperty('DateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['DateCreated'], 'Date');
      if (data.hasOwnProperty('DateLastEdited'))
        obj.dateLastEdited = ApiClient.convertToType(data['DateLastEdited'], 'Date');
      if (data.hasOwnProperty('PrintCostExcludingSalesTax'))
        obj.printCostExcludingSalesTax = ApiClient.convertToType(data['PrintCostExcludingSalesTax'], 'Number');
      if (data.hasOwnProperty('PrintCostSalesTax'))
        obj.printCostSalesTax = ApiClient.convertToType(data['PrintCostSalesTax'], 'Number');
      if (data.hasOwnProperty('TotalExcludingSalesTax'))
        obj.totalExcludingSalesTax = ApiClient.convertToType(data['TotalExcludingSalesTax'], 'Number');
      if (data.hasOwnProperty('TotalSalesTax'))
        obj.totalSalesTax = ApiClient.convertToType(data['TotalSalesTax'], 'Number');
      if (data.hasOwnProperty('IsPaid'))
        obj.isPaid = ApiClient.convertToType(data['IsPaid'], 'Boolean');
      if (data.hasOwnProperty('DateCreatedString'))
        obj.dateCreatedString = ApiClient.convertToType(data['DateCreatedString'], 'String');
      if (data.hasOwnProperty('DateLastEditedString'))
        obj.dateLastEditedString = ApiClient.convertToType(data['DateLastEditedString'], 'String');
    }
    return obj;
  }

  exports.prototype = Object.create(OrderBase.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {Array.<module:model/OrderItemResponse>} orderItems
   */
  exports.prototype.orderItems = undefined;

  /**
   * @member {module:model/OrderState} orderState
   */
  exports.prototype.orderState = undefined;

  /**
   * @member {Date} dateCreated
   */
  exports.prototype.dateCreated = undefined;

  /**
   * @member {Date} dateLastEdited
   */
  exports.prototype.dateLastEdited = undefined;

  /**
   * @member {Number} printCostExcludingSalesTax
   */
  exports.prototype.printCostExcludingSalesTax = undefined;

  /**
   * @member {Number} printCostSalesTax
   */
  exports.prototype.printCostSalesTax = undefined;

  /**
   * @member {Number} totalExcludingSalesTax
   */
  exports.prototype.totalExcludingSalesTax = undefined;

  /**
   * @member {Number} totalSalesTax
   */
  exports.prototype.totalSalesTax = undefined;

  /**
   * @member {Boolean} isPaid
   */
  exports.prototype.isPaid = undefined;

  /**
   * @member {String} dateCreatedString
   */
  exports.prototype.dateCreatedString = undefined;

  /**
   * @member {String} dateLastEditedString
   */
  exports.prototype.dateLastEditedString = undefined;


  return exports;

}));
