/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SortDirection'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SortDirection'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.SortDescriptor = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.SortDirection);
  }
}(this, function(ApiClient, SortDirection) {
  'use strict';

  /**
   * The SortDescriptor model module.
   * @module model/SortDescriptor
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SortDescriptor</code>.
   * @alias module:model/SortDescriptor
   * @class
   * @param sortDirection {module:model/SortDirection} 
   */
  var exports = function(sortDirection) {
    this.sortDirection = sortDirection;
  };

  /**
   * Constructs a <code>SortDescriptor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SortDescriptor} obj Optional instance to populate.
   * @return {module:model/SortDescriptor} The populated <code>SortDescriptor</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Member'))
        obj.member = ApiClient.convertToType(data['Member'], 'String');
      if (data.hasOwnProperty('SortDirection'))
        obj.sortDirection = SortDirection.constructFromObject(data['SortDirection']);
    }
    return obj;
  }

  /**
   * @member {String} member
   */
  exports.prototype.member = undefined;

  /**
   * @member {module:model/SortDirection} sortDirection
   */
  exports.prototype.sortDirection = undefined;


  return exports;

}));
