/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiWebhookKind', 'model/WebhookBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApiWebhookKind'), require('./WebhookBase'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.WebhookTest = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.ApiWebhookKind, root.Apicreativehubio.WebhookBase);
  }
}(this, function(ApiClient, ApiWebhookKind, WebhookBase) {
  'use strict';

  /**
   * The WebhookTest model module.
   * @module model/WebhookTest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WebhookTest</code>.
   * @alias module:model/WebhookTest
   * @class
   * @extends module:model/WebhookBase
   * @param version {Number} 
   * @param apiWebhookKind {module:model/ApiWebhookKind} 
   * @param eventUtc {Date} 
   */
  var exports = function(version, apiWebhookKind, eventUtc) {
    WebhookBase.call(this, version, apiWebhookKind, eventUtc);
    this.version = version;
    this.apiWebhookKind = apiWebhookKind;
  };

  /**
   * Constructs a <code>WebhookTest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookTest} obj Optional instance to populate.
   * @return {module:model/WebhookTest} The populated <code>WebhookTest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      WebhookBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('Version'))
        obj.version = ApiClient.convertToType(data['Version'], 'Number');
      if (data.hasOwnProperty('ApiWebhookKind'))
        obj.apiWebhookKind = ApiWebhookKind.constructFromObject(data['ApiWebhookKind']);
    }
    return obj;
  }

  exports.prototype = Object.create(WebhookBase.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {Number} version
   */
  exports.prototype.version = undefined;

  /**
   * @member {module:model/ApiWebhookKind} apiWebhookKind
   */
  exports.prototype.apiWebhookKind = undefined;


  return exports;

}));
