/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CollectionRequest', 'model/CollectionResultOfDeliveryOption', 'model/DeliveryOption'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CollectionRequest'), require('../model/CollectionResultOfDeliveryOption'), require('../model/DeliveryOption'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.DeliveryOptionsApi = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.CollectionRequest, root.Apicreativehubio.CollectionResultOfDeliveryOption, root.Apicreativehubio.DeliveryOption);
  }
}(this, function(ApiClient, CollectionRequest, CollectionResultOfDeliveryOption, DeliveryOption) {
  'use strict';

  /**
   * DeliveryOptions service.
   * @module api/DeliveryOptionsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DeliveryOptionsApi. 
   * @alias module:api/DeliveryOptionsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deliveryOptionsGetV1 operation.
     * @callback module:api/DeliveryOptionsApi~deliveryOptionsGetV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/DeliveryOption} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a delivery option given an id
     * @param {Number} id 
     * @param {module:api/DeliveryOptionsApi~deliveryOptionsGetV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeliveryOption}
     */
    this.deliveryOptionsGetV1 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deliveryOptionsGetV1");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DeliveryOption;

      return this.apiClient.callApi(
        '/api/v1/deliveryoptions/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deliveryOptionsQueryV1 operation.
     * @callback module:api/DeliveryOptionsApi~deliveryOptionsQueryV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/CollectionResultOfDeliveryOption} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Queries all delivery options for all countries
     * @param {Object} opts Optional parameters
     * @param {module:model/CollectionRequest} opts.request 
     * @param {module:api/DeliveryOptionsApi~deliveryOptionsQueryV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CollectionResultOfDeliveryOption}
     */
    this.deliveryOptionsQueryV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['request'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CollectionResultOfDeliveryOption;

      return this.apiClient.callApi(
        '/api/v1/deliveryoptions/query', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
