/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CollectionRequest', 'model/CollectionResultOfOrderConfirmedResponse', 'model/OrderConfirmedRequest', 'model/OrderConfirmedResponse', 'model/OrderEmbryonicRequest', 'model/OrderEmbryonicResponse', 'model/OrderStateRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CollectionRequest'), require('../model/CollectionResultOfOrderConfirmedResponse'), require('../model/OrderConfirmedRequest'), require('../model/OrderConfirmedResponse'), require('../model/OrderEmbryonicRequest'), require('../model/OrderEmbryonicResponse'), require('../model/OrderStateRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.OrdersApi = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.CollectionRequest, root.Apicreativehubio.CollectionResultOfOrderConfirmedResponse, root.Apicreativehubio.OrderConfirmedRequest, root.Apicreativehubio.OrderConfirmedResponse, root.Apicreativehubio.OrderEmbryonicRequest, root.Apicreativehubio.OrderEmbryonicResponse, root.Apicreativehubio.OrderStateRequest);
  }
}(this, function(ApiClient, CollectionRequest, CollectionResultOfOrderConfirmedResponse, OrderConfirmedRequest, OrderConfirmedResponse, OrderEmbryonicRequest, OrderEmbryonicResponse, OrderStateRequest) {
  'use strict';

  /**
   * Orders service.
   * @module api/OrdersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new OrdersApi. 
   * @alias module:api/OrdersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the ordersConfirmV1 operation.
     * @callback module:api/OrdersApi~ordersConfirmV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderConfirmedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a confirmed order
     * @param {Object} opts Optional parameters
     * @param {module:model/OrderConfirmedRequest} opts.model 
     * @param {module:api/OrdersApi~ordersConfirmV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderConfirmedResponse}
     */
    this.ordersConfirmV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['model'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OrderConfirmedResponse;

      return this.apiClient.callApi(
        '/api/v1/orders/confirmed', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ordersDeleteV1 operation.
     * @callback module:api/OrdersApi~ordersDeleteV1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel an embryonic order
     * @param {Number} id 
     * @param {module:api/OrdersApi~ordersDeleteV1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.ordersDeleteV1 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling ordersDeleteV1");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/orders/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ordersEmbryonicV1 operation.
     * @callback module:api/OrdersApi~ordersEmbryonicV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderEmbryonicResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create an embryonic order
     * @param {Object} opts Optional parameters
     * @param {module:model/OrderEmbryonicRequest} opts.model 
     * @param {module:api/OrdersApi~ordersEmbryonicV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderEmbryonicResponse}
     */
    this.ordersEmbryonicV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['model'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OrderEmbryonicResponse;

      return this.apiClient.callApi(
        '/api/v1/orders/embryonic', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ordersGetV1 operation.
     * @callback module:api/OrdersApi~ordersGetV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderConfirmedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get an order given an id
     * @param {Number} id 
     * @param {module:api/OrdersApi~ordersGetV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderConfirmedResponse}
     */
    this.ordersGetV1 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling ordersGetV1");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OrderConfirmedResponse;

      return this.apiClient.callApi(
        '/api/v1/orders/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ordersQueryV1 operation.
     * @callback module:api/OrdersApi~ordersQueryV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/CollectionResultOfOrderConfirmedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Queries all your orders
     * @param {Object} opts Optional parameters
     * @param {module:model/CollectionRequest} opts.request 
     * @param {module:api/OrdersApi~ordersQueryV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CollectionResultOfOrderConfirmedResponse}
     */
    this.ordersQueryV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['request'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CollectionResultOfOrderConfirmedResponse;

      return this.apiClient.callApi(
        '/api/v1/orders/query', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ordersUpdateStateV1 operation.
     * @callback module:api/OrdersApi~ordersUpdateStateV1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Only for test deployments, not for production use - update an order's state
     * @param {Object} opts Optional parameters
     * @param {module:model/OrderStateRequest} opts.model 
     * @param {module:api/OrdersApi~ordersUpdateStateV1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.ordersUpdateStateV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['model'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/orders/state', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
