/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderItemRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/OrderItemRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.SkusApi = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.OrderItemRequest);
  }
}(this, function(ApiClient, OrderItemRequest) {
  'use strict';

  /**
   * Skus service.
   * @module api/SkusApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SkusApi. 
   * @alias module:api/SkusApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the skusGetV1 operation.
     * @callback module:api/SkusApi~skusGetV1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderItemRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get an Order Item given a SKU
     * @param {String} sku 
     * @param {module:api/SkusApi~skusGetV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderItemRequest}
     */
    this.skusGetV1 = function(sku, callback) {
      var postBody = null;

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling skusGetV1");
      }


      var pathParams = {
        'sku': sku
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OrderItemRequest;

      return this.apiClient.callApi(
        '/api/v1/skus/{sku}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
