/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WebhookBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/WebhookBase'));
  } else {
    // Browser globals (root is window)
    if (!root.Apicreativehubio) {
      root.Apicreativehubio = {};
    }
    root.Apicreativehubio.WebhookClientApi = factory(root.Apicreativehubio.ApiClient, root.Apicreativehubio.WebhookBase);
  }
}(this, function(ApiClient, WebhookBase) {
  'use strict';

  /**
   * WebhookClient service.
   * @module api/WebhookClientApi
   * @version 1.0.0
   */

  /**
   * Constructs a new WebhookClientApi. 
   * @alias module:api/WebhookClientApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the webhookClientWebhookV1 operation.
     * @callback module:api/WebhookClientApi~webhookClientWebhookV1Callback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * example of webhook reciever endpoint
     * @param {Object} opts Optional parameters
     * @param {module:model/WebhookBase} opts.payload 
     * @param {module:api/WebhookClientApi~webhookClientWebhookV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    this.webhookClientWebhookV1 = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['payload'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = File;

      return this.apiClient.callApi(
        '/client/v1/webhook', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
