/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OrderItemResponse', function() {
      beforeEach(function() {
        instance = new Apicreativehubio.OrderItemResponse();
      });

      it('should create an instance of OrderItemResponse', function() {
        // TODO: update the code to test OrderItemResponse
        expect(instance).to.be.a(Apicreativehubio.OrderItemResponse);
      });

      it('should have the property product (base name: "Product")', function() {
        // TODO: update the code to test the property product
        expect(instance).to.have.property('product');
        // expect(instance.product).to.be(expectedValueLiteral);
      });

      it('should have the property printOption (base name: "PrintOption")', function() {
        // TODO: update the code to test the property printOption
        expect(instance).to.have.property('printOption');
        // expect(instance.printOption).to.be(expectedValueLiteral);
      });

    });
  });

}));
