/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PredicateFilterDescriptor', function() {
      beforeEach(function() {
        instance = new Apicreativehubio.PredicateFilterDescriptor();
      });

      it('should create an instance of PredicateFilterDescriptor', function() {
        // TODO: update the code to test PredicateFilterDescriptor
        expect(instance).to.be.a(Apicreativehubio.PredicateFilterDescriptor);
      });

      it('should have the property member (base name: "Member")', function() {
        // TODO: update the code to test the property member
        expect(instance).to.have.property('member');
        // expect(instance.member).to.be(expectedValueLiteral);
      });

      it('should have the property predicateOperator (base name: "PredicateOperator")', function() {
        // TODO: update the code to test the property predicateOperator
        expect(instance).to.have.property('predicateOperator');
        // expect(instance.predicateOperator).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "Value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property valueKendo (base name: "ValueKendo")', function() {
        // TODO: update the code to test the property valueKendo
        expect(instance).to.have.property('valueKendo');
        // expect(instance.valueKendo).to.be(expectedValueLiteral);
      });

    });
  });

}));
