/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SortDirection', function() {
      beforeEach(function() {
        instance = Apicreativehubio.SortDirection;
      });

      it('should create an instance of SortDirection', function() {
        // TODO: update the code to test SortDirection
        expect(instance).to.be.a('object');
      });

      it('should have the property ascending', function() {
        expect(instance).to.have.property('ascending');
        expect(instance.ascending).to.be("Ascending");
      });

      it('should have the property descending', function() {
        expect(instance).to.have.property('descending');
        expect(instance.descending).to.be("Descending");
      });

    });
  });

}));
