/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WebhookOrderStateChanged', function() {
      beforeEach(function() {
        instance = new Apicreativehubio.WebhookOrderStateChanged();
      });

      it('should create an instance of WebhookOrderStateChanged', function() {
        // TODO: update the code to test WebhookOrderStateChanged
        expect(instance).to.be.a(Apicreativehubio.WebhookOrderStateChanged);
      });

      it('should have the property version (base name: "Version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property apiWebhookKind (base name: "ApiWebhookKind")', function() {
        // TODO: update the code to test the property apiWebhookKind
        expect(instance).to.have.property('apiWebhookKind');
        // expect(instance.apiWebhookKind).to.be(expectedValueLiteral);
      });

      it('should have the property order (base name: "Order")', function() {
        // TODO: update the code to test the property order
        expect(instance).to.have.property('order');
        // expect(instance.order).to.be(expectedValueLiteral);
      });

    });
  });

}));
