/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/ApiWebhookKind', 'model/CollectionRequest', 'model/CollectionResultOfCountry', 'model/CollectionResultOfDeliveryOption', 'model/CollectionResultOfOrderConfirmedResponse', 'model/CollectionResultOfProduct', 'model/CompositeFilterDescriptor', 'model/Country', 'model/DeliveryOption', 'model/FilterLogicalOperator', 'model/FilterPredicateOperator', 'model/IFilterDescriptor', 'model/OrderBase', 'model/OrderConfirmedRequest', 'model/OrderConfirmedResponse', 'model/OrderEmbryonicRequest', 'model/OrderEmbryonicResponse', 'model/OrderItemBase', 'model/OrderItemRequest', 'model/OrderItemResponse', 'model/OrderRequest', 'model/OrderResponse', 'model/OrderState', 'model/OrderStateRequest', 'model/PredicateFilterDescriptor', 'model/PrintOption', 'model/Product', 'model/SortDescriptor', 'model/SortDirection', 'model/ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal', 'model/WebhookBase', 'model/WebhookOrderStateChanged', 'model/WebhookTest', 'api/CountriesApi', 'api/DeliveryOptionsApi', 'api/OrdersApi', 'api/ProductsApi', 'api/SkusApi', 'api/WebhookClientApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Address'), require('./model/ApiWebhookKind'), require('./model/CollectionRequest'), require('./model/CollectionResultOfCountry'), require('./model/CollectionResultOfDeliveryOption'), require('./model/CollectionResultOfOrderConfirmedResponse'), require('./model/CollectionResultOfProduct'), require('./model/CompositeFilterDescriptor'), require('./model/Country'), require('./model/DeliveryOption'), require('./model/FilterLogicalOperator'), require('./model/FilterPredicateOperator'), require('./model/IFilterDescriptor'), require('./model/OrderBase'), require('./model/OrderConfirmedRequest'), require('./model/OrderConfirmedResponse'), require('./model/OrderEmbryonicRequest'), require('./model/OrderEmbryonicResponse'), require('./model/OrderItemBase'), require('./model/OrderItemRequest'), require('./model/OrderItemResponse'), require('./model/OrderRequest'), require('./model/OrderResponse'), require('./model/OrderState'), require('./model/OrderStateRequest'), require('./model/PredicateFilterDescriptor'), require('./model/PrintOption'), require('./model/Product'), require('./model/SortDescriptor'), require('./model/SortDirection'), require('./model/ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal'), require('./model/WebhookBase'), require('./model/WebhookOrderStateChanged'), require('./model/WebhookTest'), require('./api/CountriesApi'), require('./api/DeliveryOptionsApi'), require('./api/OrdersApi'), require('./api/ProductsApi'), require('./api/SkusApi'), require('./api/WebhookClientApi'));
  }
}(function(ApiClient, Address, ApiWebhookKind, CollectionRequest, CollectionResultOfCountry, CollectionResultOfDeliveryOption, CollectionResultOfOrderConfirmedResponse, CollectionResultOfProduct, CompositeFilterDescriptor, Country, DeliveryOption, FilterLogicalOperator, FilterPredicateOperator, IFilterDescriptor, OrderBase, OrderConfirmedRequest, OrderConfirmedResponse, OrderEmbryonicRequest, OrderEmbryonicResponse, OrderItemBase, OrderItemRequest, OrderItemResponse, OrderRequest, OrderResponse, OrderState, OrderStateRequest, PredicateFilterDescriptor, PrintOption, Product, SortDescriptor, SortDirection, ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal, WebhookBase, WebhookOrderStateChanged, WebhookTest, CountriesApi, DeliveryOptionsApi, OrdersApi, ProductsApi, SkusApi, WebhookClientApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Apicreativehubio = require('index'); // See note below*.
   * var xxxSvc = new Apicreativehubio.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Apicreativehubio.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Apicreativehubio.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Apicreativehubio.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address: Address,
    /**
     * The ApiWebhookKind model constructor.
     * @property {module:model/ApiWebhookKind}
     */
    ApiWebhookKind: ApiWebhookKind,
    /**
     * The CollectionRequest model constructor.
     * @property {module:model/CollectionRequest}
     */
    CollectionRequest: CollectionRequest,
    /**
     * The CollectionResultOfCountry model constructor.
     * @property {module:model/CollectionResultOfCountry}
     */
    CollectionResultOfCountry: CollectionResultOfCountry,
    /**
     * The CollectionResultOfDeliveryOption model constructor.
     * @property {module:model/CollectionResultOfDeliveryOption}
     */
    CollectionResultOfDeliveryOption: CollectionResultOfDeliveryOption,
    /**
     * The CollectionResultOfOrderConfirmedResponse model constructor.
     * @property {module:model/CollectionResultOfOrderConfirmedResponse}
     */
    CollectionResultOfOrderConfirmedResponse: CollectionResultOfOrderConfirmedResponse,
    /**
     * The CollectionResultOfProduct model constructor.
     * @property {module:model/CollectionResultOfProduct}
     */
    CollectionResultOfProduct: CollectionResultOfProduct,
    /**
     * The CompositeFilterDescriptor model constructor.
     * @property {module:model/CompositeFilterDescriptor}
     */
    CompositeFilterDescriptor: CompositeFilterDescriptor,
    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country: Country,
    /**
     * The DeliveryOption model constructor.
     * @property {module:model/DeliveryOption}
     */
    DeliveryOption: DeliveryOption,
    /**
     * The FilterLogicalOperator model constructor.
     * @property {module:model/FilterLogicalOperator}
     */
    FilterLogicalOperator: FilterLogicalOperator,
    /**
     * The FilterPredicateOperator model constructor.
     * @property {module:model/FilterPredicateOperator}
     */
    FilterPredicateOperator: FilterPredicateOperator,
    /**
     * The IFilterDescriptor model constructor.
     * @property {module:model/IFilterDescriptor}
     */
    IFilterDescriptor: IFilterDescriptor,
    /**
     * The OrderBase model constructor.
     * @property {module:model/OrderBase}
     */
    OrderBase: OrderBase,
    /**
     * The OrderConfirmedRequest model constructor.
     * @property {module:model/OrderConfirmedRequest}
     */
    OrderConfirmedRequest: OrderConfirmedRequest,
    /**
     * The OrderConfirmedResponse model constructor.
     * @property {module:model/OrderConfirmedResponse}
     */
    OrderConfirmedResponse: OrderConfirmedResponse,
    /**
     * The OrderEmbryonicRequest model constructor.
     * @property {module:model/OrderEmbryonicRequest}
     */
    OrderEmbryonicRequest: OrderEmbryonicRequest,
    /**
     * The OrderEmbryonicResponse model constructor.
     * @property {module:model/OrderEmbryonicResponse}
     */
    OrderEmbryonicResponse: OrderEmbryonicResponse,
    /**
     * The OrderItemBase model constructor.
     * @property {module:model/OrderItemBase}
     */
    OrderItemBase: OrderItemBase,
    /**
     * The OrderItemRequest model constructor.
     * @property {module:model/OrderItemRequest}
     */
    OrderItemRequest: OrderItemRequest,
    /**
     * The OrderItemResponse model constructor.
     * @property {module:model/OrderItemResponse}
     */
    OrderItemResponse: OrderItemResponse,
    /**
     * The OrderRequest model constructor.
     * @property {module:model/OrderRequest}
     */
    OrderRequest: OrderRequest,
    /**
     * The OrderResponse model constructor.
     * @property {module:model/OrderResponse}
     */
    OrderResponse: OrderResponse,
    /**
     * The OrderState model constructor.
     * @property {module:model/OrderState}
     */
    OrderState: OrderState,
    /**
     * The OrderStateRequest model constructor.
     * @property {module:model/OrderStateRequest}
     */
    OrderStateRequest: OrderStateRequest,
    /**
     * The PredicateFilterDescriptor model constructor.
     * @property {module:model/PredicateFilterDescriptor}
     */
    PredicateFilterDescriptor: PredicateFilterDescriptor,
    /**
     * The PrintOption model constructor.
     * @property {module:model/PrintOption}
     */
    PrintOption: PrintOption,
    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product: Product,
    /**
     * The SortDescriptor model constructor.
     * @property {module:model/SortDescriptor}
     */
    SortDescriptor: SortDescriptor,
    /**
     * The SortDirection model constructor.
     * @property {module:model/SortDirection}
     */
    SortDirection: SortDirection,
    /**
     * The ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal model constructor.
     * @property {module:model/ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal}
     */
    ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal: ValueTupleOfDecimalAndDecimalAndDecimalAndDecimal,
    /**
     * The WebhookBase model constructor.
     * @property {module:model/WebhookBase}
     */
    WebhookBase: WebhookBase,
    /**
     * The WebhookOrderStateChanged model constructor.
     * @property {module:model/WebhookOrderStateChanged}
     */
    WebhookOrderStateChanged: WebhookOrderStateChanged,
    /**
     * The WebhookTest model constructor.
     * @property {module:model/WebhookTest}
     */
    WebhookTest: WebhookTest,
    /**
     * The CountriesApi service constructor.
     * @property {module:api/CountriesApi}
     */
    CountriesApi: CountriesApi,
    /**
     * The DeliveryOptionsApi service constructor.
     * @property {module:api/DeliveryOptionsApi}
     */
    DeliveryOptionsApi: DeliveryOptionsApi,
    /**
     * The OrdersApi service constructor.
     * @property {module:api/OrdersApi}
     */
    OrdersApi: OrdersApi,
    /**
     * The ProductsApi service constructor.
     * @property {module:api/ProductsApi}
     */
    ProductsApi: ProductsApi,
    /**
     * The SkusApi service constructor.
     * @property {module:api/SkusApi}
     */
    SkusApi: SkusApi,
    /**
     * The WebhookClientApi service constructor.
     * @property {module:api/WebhookClientApi}
     */
    WebhookClientApi: WebhookClientApi
  };

  return exports;
}));
