/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apicreativehubio.DeliveryOptionsApi();
  });

  describe('(package)', function() {
    describe('DeliveryOptionsApi', function() {
      describe('deliveryOptionsGetV1', function() {
        it('should call deliveryOptionsGetV1 successfully', function(done) {
          // TODO: uncomment, update parameter values for deliveryOptionsGetV1 call and complete the assertions
          /*
          var id = 56;

          instance.deliveryOptionsGetV1(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apicreativehubio.DeliveryOption);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.branchId).to.be.a('number');
            expect(data.branchId).to.be(0);
            expect(data.branchName).to.be.a('string');
            expect(data.branchName).to.be("");
            expect(data.method).to.be.a('string');
            expect(data.method).to.be("");
            expect(data.deliveryTime).to.be.a('string');
            expect(data.deliveryTime).to.be("");
            expect(data.deliveryChargeExcludingSalesTax).to.be.a('number');
            expect(data.deliveryChargeExcludingSalesTax).to.be();
            expect(data.deliveryChargeSalesTax).to.be.a('number');
            expect(data.deliveryChargeSalesTax).to.be();
            expect(data.estimatedDeliveryDateFrom).to.be.a(Date);
            expect(data.estimatedDeliveryDateFrom).to.be(new Date());
            expect(data.estimatedDeliveryDateTo).to.be.a(Date);
            expect(data.estimatedDeliveryDateTo).to.be(new Date());

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deliveryOptionsQueryV1', function() {
        it('should call deliveryOptionsQueryV1 successfully', function(done) {
          // TODO: uncomment, update parameter values for deliveryOptionsQueryV1 call and complete the assertions
          /*
          var opts = {};
          opts.request = new Apicreativehubio.CollectionRequest();
          opts.request.page = 0;
          opts.request.pageSize = 0;
          opts.request.filter = new Apicreativehubio.IFilterDescriptor();
          opts.request.sorts = [new Apicreativehubio.SortDescriptor()];
          opts.request.sorts[0].member = "";
          opts.request.sorts[0].sortDirection = new Apicreativehubio.SortDirection();

          instance.deliveryOptionsQueryV1(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apicreativehubio.CollectionResultOfDeliveryOption);
            {
              let dataCtr = data.data;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Apicreativehubio.DeliveryOption);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.branchId).to.be.a('number');
                expect(data.branchId).to.be(0);
                expect(data.branchName).to.be.a('string');
                expect(data.branchName).to.be("");
                expect(data.method).to.be.a('string');
                expect(data.method).to.be("");
                expect(data.deliveryTime).to.be.a('string');
                expect(data.deliveryTime).to.be("");
                expect(data.deliveryChargeExcludingSalesTax).to.be.a('number');
                expect(data.deliveryChargeExcludingSalesTax).to.be();
                expect(data.deliveryChargeSalesTax).to.be.a('number');
                expect(data.deliveryChargeSalesTax).to.be();
                expect(data.estimatedDeliveryDateFrom).to.be.a(Date);
                expect(data.estimatedDeliveryDateFrom).to.be(new Date());
                expect(data.estimatedDeliveryDateTo).to.be.a(Date);
                expect(data.estimatedDeliveryDateTo).to.be(new Date());

                      }
            }
            expect(data.total).to.be.a('number');
            expect(data.total).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
