/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apicreativehubio.SkusApi();
  });

  describe('(package)', function() {
    describe('SkusApi', function() {
      describe('skusGetV1', function() {
        it('should call skusGetV1 successfully', function(done) {
          // TODO: uncomment, update parameter values for skusGetV1 call and complete the assertions
          /*
          var sku = "sku_example";

          instance.skusGetV1(sku, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apicreativehubio.OrderItemRequest);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.productId).to.be.a('number');
            expect(data.productId).to.be(0);
            expect(data.printOptionId).to.be.a('number');
            expect(data.printOptionId).to.be(0);
            expect(data.quantity).to.be.a('number');
            expect(data.quantity).to.be(0);
            expect(data.externalReference).to.be.a('string');
            expect(data.externalReference).to.be("");
            expect(data.externalSku).to.be.a('string');
            expect(data.externalSku).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
