/*
 * api.creativehub.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apicreativehubio);
  }
}(this, function(expect, Apicreativehubio) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apicreativehubio.WebhookClientApi();
  });

  describe('(package)', function() {
    describe('WebhookClientApi', function() {
      describe('webhookClientWebhookV1', function() {
        it('should call webhookClientWebhookV1 successfully', function(done) {
          // TODO: uncomment, update parameter values for webhookClientWebhookV1 call and complete the assertions
          /*
          var opts = {};
          opts.payload = new Apicreativehubio.WebhookBase();
          opts.payload.version = 0;
          opts.payload.apiWebhookKind = new Apicreativehubio.ApiWebhookKind();
          opts.payload.eventUtc = new Date();
          opts.payload.salt = "";

          instance.webhookClientWebhookV1(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(File);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
